package com.browsewhat.app.db.entities;

// Generated Dec 31, 2014 1:31:02 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BwBankBranchLocationMap generated by hbm2java
 */
@Entity
@Table(name = "bw_bank_branch_location_map", catalog = "browsewhat")
public class BwBankBranchLocationMap implements java.io.Serializable {

    private Integer      id;
    private BwBankBranch bwBankBranch;
    private String       lati;
    private String       longi;
    private Character    isAccurate;

    public BwBankBranchLocationMap() {
    }

    public BwBankBranchLocationMap(BwBankBranch bwBankBranch) {
        this.bwBankBranch = bwBankBranch;
    }

    public BwBankBranchLocationMap(BwBankBranch bwBankBranch, String lati, String longi, Character isAccurate) {
        this.bwBankBranch = bwBankBranch;
        this.lati = lati;
        this.longi = longi;
        this.isAccurate = isAccurate;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "branch_id", nullable = false)
    public BwBankBranch getBwBankBranch() {
        return this.bwBankBranch;
    }

    public void setBwBankBranch(BwBankBranch bwBankBranch) {
        this.bwBankBranch = bwBankBranch;
    }

    @Column(name = "lati", length = 45)
    public String getLati() {
        return this.lati;
    }

    public void setLati(String lati) {
        this.lati = lati;
    }

    @Column(name = "longi", length = 45)
    public String getLongi() {
        return this.longi;
    }

    public void setLongi(String longi) {
        this.longi = longi;
    }

    @Column(name = "is_accurate", length = 1)
    public Character getIsAccurate() {
        return this.isAccurate;
    }

    public void setIsAccurate(Character isAccurate) {
        this.isAccurate = isAccurate;
    }

}
