package com.browsewhat.app.db.entities;

// Generated Jan 2, 2015 5:42:03 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * BwBankBranch generated by hbm2java
 */
@Entity
@Table(name = "bw_bank_branch", catalog = "browsewhat", uniqueConstraints = { @UniqueConstraint(columnNames = "ifsc"),
        @UniqueConstraint(columnNames = "micr") })
public class BwBankBranch implements java.io.Serializable {

    private Integer                      id;
    private BwBankInfo                   bwBankInfo;
    private String                       branch;
    private String                       address;
    private String                       city;
    private String                       district;
    private String                       state;
    private String                       ifsc;
    private String                       micr;
    private Set<BwBankBranchLocationMap> bwBankBranchLocationMaps = new HashSet<BwBankBranchLocationMap>(0);

    public BwBankBranch() {
    }

    public BwBankBranch(BwBankInfo bwBankInfo, String branch, String address, String city, String district, String state, String ifsc) {
        this.bwBankInfo = bwBankInfo;
        this.branch = branch;
        this.address = address;
        this.city = city;
        this.district = district;
        this.state = state;
        this.ifsc = ifsc;
    }

    public BwBankBranch(BwBankInfo bwBankInfo, String branch, String address, String city, String district, String state, String ifsc,
            String micr, Set<BwBankBranchLocationMap> bwBankBranchLocationMaps) {
        this.bwBankInfo = bwBankInfo;
        this.branch = branch;
        this.address = address;
        this.city = city;
        this.district = district;
        this.state = state;
        this.ifsc = ifsc;
        this.micr = micr;
        this.bwBankBranchLocationMaps = bwBankBranchLocationMaps;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "bank_id", nullable = false)
    public BwBankInfo getBwBankInfo() {
        return this.bwBankInfo;
    }

    public void setBwBankInfo(BwBankInfo bwBankInfo) {
        this.bwBankInfo = bwBankInfo;
    }

    @Column(name = "branch", nullable = false, length = 150)
    public String getBranch() {
        return this.branch;
    }

    public void setBranch(String branch) {
        this.branch = branch;
    }

    @Column(name = "address", nullable = false, length = 250)
    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Column(name = "city", nullable = false, length = 100)
    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    @Column(name = "district", nullable = false, length = 100)
    public String getDistrict() {
        return this.district;
    }

    public void setDistrict(String district) {
        this.district = district;
    }

    @Column(name = "state", nullable = false, length = 45)
    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    @Column(name = "ifsc", unique = true, nullable = false, length = 45)
    public String getIfsc() {
        return this.ifsc;
    }

    public void setIfsc(String ifsc) {
        this.ifsc = ifsc;
    }

    @Column(name = "micr", unique = true, length = 45)
    public String getMicr() {
        return this.micr;
    }

    public void setMicr(String micr) {
        this.micr = micr;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "bwBankBranch")
    public Set<BwBankBranchLocationMap> getBwBankBranchLocationMaps() {
        return this.bwBankBranchLocationMaps;
    }

    public void setBwBankBranchLocationMaps(Set<BwBankBranchLocationMap> bwBankBranchLocationMaps) {
        this.bwBankBranchLocationMaps = bwBankBranchLocationMaps;
    }

}
