package com.browsewhat.app.db.entities;

// Generated Jan 15, 2015 1:30:53 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BwCategory generated by hbm2java
 */
@Entity
@Table(name = "bw_category", catalog = "browsewhat")
public class BwCategory implements java.io.Serializable {

    private Integer         id;
    private BwCategory      bwCategory;
    private String          category;
    private char            isPublic;
    private String          url;
    private Set<BwModules>  bwModuleses  = new HashSet<BwModules>(0);
    private Set<BwCategory> bwCategories = new HashSet<BwCategory>(0);

    public BwCategory() {
    }

    public BwCategory(String category, char isPublic, String url) {
        this.category = category;
        this.isPublic = isPublic;
        this.url = url;
    }

    public BwCategory(BwCategory bwCategory, String category, char isPublic, String url, Set<BwModules> bwModuleses, Set<BwCategory> bwCategories) {
        this.bwCategory = bwCategory;
        this.category = category;
        this.isPublic = isPublic;
        this.url = url;
        this.bwModuleses = bwModuleses;
        this.bwCategories = bwCategories;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "parent_category")
    public BwCategory getBwCategory() {
        return this.bwCategory;
    }

    public void setBwCategory(BwCategory bwCategory) {
        this.bwCategory = bwCategory;
    }

    @Column(name = "category", nullable = false, length = 100)
    public String getCategory() {
        return this.category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    @Column(name = "is_public", nullable = false, length = 1)
    public char getIsPublic() {
        return this.isPublic;
    }

    public void setIsPublic(char isPublic) {
        this.isPublic = isPublic;
    }

    @Column(name = "url", nullable = false, length = 45)
    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "bwCategory")
    public Set<BwModules> getBwModuleses() {
        return this.bwModuleses;
    }

    public void setBwModuleses(Set<BwModules> bwModuleses) {
        this.bwModuleses = bwModuleses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "bwCategory")
    public Set<BwCategory> getBwCategories() {
        return this.bwCategories;
    }

    public void setBwCategories(Set<BwCategory> bwCategories) {
        this.bwCategories = bwCategories;
    }

}
