package com.browsewhat.app.db.entities;

// Generated Jan 15, 2015 1:30:53 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BwModules generated by hbm2java
 */
@Entity
@Table(name = "bw_modules", catalog = "browsewhat")
public class BwModules implements java.io.Serializable {

    private Integer    id;
    private BwCategory bwCategory;
    private String     moduleName;
    private String     url;
    private Date       started;
    private String     image;

    public BwModules() {
    }

    public BwModules(BwCategory bwCategory, String moduleName, String url, Date started, String image) {
        this.bwCategory = bwCategory;
        this.moduleName = moduleName;
        this.url = url;
        this.started = started;
        this.image = image;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category", nullable = false)
    public BwCategory getBwCategory() {
        return this.bwCategory;
    }

    public void setBwCategory(BwCategory bwCategory) {
        this.bwCategory = bwCategory;
    }

    @Column(name = "module_name", nullable = false, length = 100)
    public String getModuleName() {
        return this.moduleName;
    }

    public void setModuleName(String moduleName) {
        this.moduleName = moduleName;
    }

    @Column(name = "url", nullable = false, length = 45)
    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "started", nullable = false, length = 19)
    public Date getStarted() {
        return this.started;
    }

    public void setStarted(Date started) {
        this.started = started;
    }

    @Column(name = "image", nullable = false, length = 45)
    public String getImage() {
        return this.image;
    }

    public void setImage(String image) {
        this.image = image;
    }

}
