package com.browsewhat.app.db.entities;

// Generated Dec 29, 2014 4:56:20 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BwRoles generated by hbm2java
 */
@Entity
@Table(name = "bw_roles", catalog = "browsewhat")
public class BwRoles implements java.io.Serializable {

	private Integer id;
	private char regularUser;
	private char organization;
	private char employee;
	private char admin;
	private char superAdmin;
	private char test;
	private Set<BwUserRole> bwUserRoles = new HashSet<BwUserRole>(0);

	public BwRoles() {
	}

	public BwRoles(char regularUser, char organization, char employee,
			char admin, char superAdmin, char test) {
		this.regularUser = regularUser;
		this.organization = organization;
		this.employee = employee;
		this.admin = admin;
		this.superAdmin = superAdmin;
		this.test = test;
	}

	public BwRoles(char regularUser, char organization, char employee,
			char admin, char superAdmin, char test, Set<BwUserRole> bwUserRoles) {
		this.regularUser = regularUser;
		this.organization = organization;
		this.employee = employee;
		this.admin = admin;
		this.superAdmin = superAdmin;
		this.test = test;
		this.bwUserRoles = bwUserRoles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "regular_user", nullable = false, length = 1)
	public char getRegularUser() {
		return this.regularUser;
	}

	public void setRegularUser(char regularUser) {
		this.regularUser = regularUser;
	}

	@Column(name = "organization", nullable = false, length = 1)
	public char getOrganization() {
		return this.organization;
	}

	public void setOrganization(char organization) {
		this.organization = organization;
	}

	@Column(name = "employee", nullable = false, length = 1)
	public char getEmployee() {
		return this.employee;
	}

	public void setEmployee(char employee) {
		this.employee = employee;
	}

	@Column(name = "admin", nullable = false, length = 1)
	public char getAdmin() {
		return this.admin;
	}

	public void setAdmin(char admin) {
		this.admin = admin;
	}

	@Column(name = "super_admin", nullable = false, length = 1)
	public char getSuperAdmin() {
		return this.superAdmin;
	}

	public void setSuperAdmin(char superAdmin) {
		this.superAdmin = superAdmin;
	}

	@Column(name = "test", nullable = false, length = 1)
	public char getTest() {
		return this.test;
	}

	public void setTest(char test) {
		this.test = test;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bwRoles")
	public Set<BwUserRole> getBwUserRoles() {
		return this.bwUserRoles;
	}

	public void setBwUserRoles(Set<BwUserRole> bwUserRoles) {
		this.bwUserRoles = bwUserRoles;
	}

}
