package com.browsewhat.app.db.entities;

// Generated Jan 2, 2015 5:42:03 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BwUserRole generated by hbm2java
 */
@Entity
@Table(name = "bw_user_role", catalog = "browsewhat")
public class BwUserRole implements java.io.Serializable {

    private Integer id;
    private BwRoles bwRoles;
    private BwUser  bwUser;
    private Date    expires;

    public BwUserRole() {
    }

    public BwUserRole(BwRoles bwRoles, BwUser bwUser, Date expires) {
        this.bwRoles = bwRoles;
        this.bwUser = bwUser;
        this.expires = expires;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "role_id", nullable = false)
    public BwRoles getBwRoles() {
        return this.bwRoles;
    }

    public void setBwRoles(BwRoles bwRoles) {
        this.bwRoles = bwRoles;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    public BwUser getBwUser() {
        return this.bwUser;
    }

    public void setBwUser(BwUser bwUser) {
        this.bwUser = bwUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "expires", nullable = false, length = 19)
    public Date getExpires() {
        return this.expires;
    }

    public void setExpires(Date expires) {
        this.expires = expires;
    }

}
