package com.browsewhat.app.db.entities;

// Generated Jan 15, 2015 1:30:53 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name = "country", catalog = "browsewhat")
public class Country implements java.io.Serializable {

    private Integer    id;
    private String     name;
    private String     capital;
    private String     website;
    private String     flag;
    private Set<State> states = new HashSet<State>(0);

    public Country() {
    }

    public Country(String name, String capital, String website, String flag) {
        this.name = name;
        this.capital = capital;
        this.website = website;
        this.flag = flag;
    }

    public Country(String name, String capital, String website, String flag, Set<State> states) {
        this.name = name;
        this.capital = capital;
        this.website = website;
        this.flag = flag;
        this.states = states;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "name", nullable = false, length = 45)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "capital", nullable = false, length = 45)
    public String getCapital() {
        return this.capital;
    }

    public void setCapital(String capital) {
        this.capital = capital;
    }

    @Column(name = "website", nullable = false, length = 100)
    public String getWebsite() {
        return this.website;
    }

    public void setWebsite(String website) {
        this.website = website;
    }

    @Column(name = "flag", nullable = false, length = 45)
    public String getFlag() {
        return this.flag;
    }

    public void setFlag(String flag) {
        this.flag = flag;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "country")
    public Set<State> getStates() {
        return this.states;
    }

    public void setStates(Set<State> states) {
        this.states = states;
    }

}
