package com.browsewhat.app.db.entities;

// Generated Jan 15, 2015 1:30:53 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * State generated by hbm2java
 */
@Entity
@Table(name = "state", catalog = "browsewhat")
public class State implements java.io.Serializable {

    private Integer       id;
    private Country       country;
    private String        name;
    private String        capital;
    private Integer       geoLocation;
    private Set<District> districts = new HashSet<District>(0);

    public State() {
    }

    public State(Country country, String name, String capital) {
        this.country = country;
        this.name = name;
        this.capital = capital;
    }

    public State(Country country, String name, String capital, Integer geoLocation, Set<District> districts) {
        this.country = country;
        this.name = name;
        this.capital = capital;
        this.geoLocation = geoLocation;
        this.districts = districts;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "country", nullable = false)
    public Country getCountry() {
        return this.country;
    }

    public void setCountry(Country country) {
        this.country = country;
    }

    @Column(name = "name", nullable = false, length = 70)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "capital", nullable = false, length = 70)
    public String getCapital() {
        return this.capital;
    }

    public void setCapital(String capital) {
        this.capital = capital;
    }

    @Column(name = "geo_location")
    public Integer getGeoLocation() {
        return this.geoLocation;
    }

    public void setGeoLocation(Integer geoLocation) {
        this.geoLocation = geoLocation;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "state")
    public Set<District> getDistricts() {
        return this.districts;
    }

    public void setDistricts(Set<District> districts) {
        this.districts = districts;
    }

}
